// ********* ADVISOR END POINTS *********// 

### Register
POST http://localhost:4000/api/v1/register
Content-Type: application/json

{
    "fullName":"Johm Smith",
    "email":"js@gmail.com",
    "password":"password123",
    "category":"Criminal"
}

### Login
POST http://localhost:4000/api/v1/login
Content-Type: application/json

{
    "email":"apoud3l1997@gmail.com",
    "password":"password12345" 
}

### Logout
GET http://localhost:4000/api/v1/logout

### Get all advisor
GET http://localhost:4000/api/v1/all

### Get advisor profile
GET http://localhost:4000/api/v1/profile


### Open availiability
POST http://localhost:4000/api/v1/open/availability
Content-Type: application/json

{
    "id":"639bc7058b33b6bdaf23dddd",
    "time":"5AM",
    "availableDate":"2023-01-20"
}


### Get all availability
GET http://localhost:4000/api/v1/all/availability

### Delete availability
DELETE http://localhost:4000/api/v1/delete/available/639bb45c0fe1c281d8b904be

### Forgot password
POST http://localhost:4000/api/v1/forgot/password
Content-Type: application/json

{
  "email":"apoud3l1997@gmail.com"
}


### Reset password
PUT http://localhost:4000/api/v1/reset/password/f6a4ddc4824d6e744c59ceb11dd4bcb3ff21b773
Content-Type: application/json

{
  "password":"password12345",
  "confirmPassword":"password12345"
}

// ********* BOOKINGS END POINTS  ********* //

### Create new booking
POST http://localhost:4000/api/v1/booking
Content-Type: application/json

{
    "time":"5AM",
    "availableDate":"2023-01-20",
    "lawyer":"6392c01f4c45797b3d6ff4a8",
    "userId":"639852f319b23d396ebd9eea"
}

### Get all bookings
GET http://localhost:4000/api/v1/booking

### Get bookings by Id
GET http://localhost:4000/api/v1/booking/63b2bc5221525d4db28f95ff


### Delete booking
DELETE http://localhost:4000/api/v1/delete/booking/63b62ef35c78ab7f334748a8
Content-Type: application/json

{
    "time":"2PM",
    "bookedDate":"2023-01-12",
    "lawyer":"63b55697714b1fcd3387bd49",
    "lawyerName": "John Smith",
    "lawyerEmail":"js@gmail.com",
    "userEmail":"anuppoudel60@gmail.com",
    "userName":"Anup Poudel",
    "userId":"63b2bc5221525d4db28f95ff"
}
