// ADVISOR END POINTS // 

### Register
POST http://localhost:4000/api/v1/register
Content-Type: application/json

{
    "fullName":"Anup Poudel",
    "email":"ag@gmail.com",
    "password":"password123",
    "category":"Criminal"
}

### Login
POST http://localhost:4000/api/v1/login
Content-Type: application/json

{
    "email":"ag@gmail.com",
    "password":"password123" 
}

### Logout
GET http://localhost:4000/api/v1/logout

### Get all advisor
GET http://localhost:4000/api/v1/all

### Get advisor profile
GET http://localhost:4000/api/v1/profile


### Open availiability
POST http://localhost:4000/api/v1/open/availability
Content-Type: application/json

{
    "id":"6392c01f4c45797b3d6ff4a8",
    "time":"10AM",
    "availableDate":"04/04/2022"
}


### Get all availability
GET http://localhost:4000/api/v1/all/availability

### Delete availability
DELETE http://localhost:4000/api/v1/delete/available/6392c6f1404496d15473584b
